### PR TITLE
Fixed barrel

### PR DESCRIPTION
**Pull request by cyb3rgeorge**

### CODE REVIEW

**Review by cyb3rgeorge — COMMENTED** [review]
Review

**Comment by Darr3n2GG** [comment]
bro the import file is generated after image is loaded so don't need to delete that

**Comment by Darr3n2GG** [comment]
Also cannot just make a new DummyE scene

**Comment by cyb3rgeorge** [comment]
Why?
DummyE is a script, not a new scene

**Comment by Darr3n2GG** [comment]
If I am not correct, you are using the dummyE script instead of the original dummy script for the extra dummy in a level.
Why not just make the extra dummy it's on scene since it is already not related to the original dummy?

**Comment by Darr3n2GG** [comment]
or just make a new script and then detach the original one from the extra barrel

**Comment by cyb3rgeorge** [comment]
> or just make a new script and then detach the original one from the extra barrel

I did this

**Comment by Darr3n2GG** [comment]
> > or just make a new script and then detach the original one from the extra barrel
> 
> 
> 
> I did this

Write the script in the script file not in the scene

**Comment by cyb3rgeorge** [comment]
> > > or just make a new script and then detach the original one from the extra barrel
> > 
> > 
> > I did this
> 
> Write the script in the script file not in the scene

You can do that yourself, I didnt know what you are talking about

**Comment by Darr3n2GG** [comment]
> > > > or just make a new script and then detach the original one from the extra barrel
> 
> > > 
> 
> > > 
> 
> > > I did this
> 
> > 
> 
> > Write the script in the script file not in the scene
> 
> 
> 
> You can do that yourself, I didnt know what you are talking about

Ok will merge

**Pull request merged**
