### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by cyb3rgeorge**

### CODE REVIEW

**Review by cyb3rgeorge — COMMENTED** [review]
Enhanced

**Comment by Darr3n2GG** [comment]
Please check my review

**Review by cyb3rgeorge — COMMENTED** [review]
Reviewed

**Review by cyb3rgeorge — COMMENTED** [review]
Review 2

**Review by cyb3rgeorge — COMMENTED** [review]
review

**Review by cyb3rgeorge — COMMENTED** [review]
It's back

**Comment by Darr3n2GG** [comment]
YAY

**Pull request merged**
